language: python

python:
 - 3.6

env:
 - DJANGO=2.1.4

before_install:
 - export DJANGO_SETTINGS_MODULE=inventory_management.settings

install:
 - pip3 install -r requirements.txt
 - pip3 install black

before_script:
 - python3 src/manage.py makemigrations
 - python3 src/manage.py migrate

script:
 - black --check src/
 - python3 src/manage.py test
